blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/enrique-lozano/F1-World-API/discussions/categories/ideas-new-features
    about: Share your ideas about new features that you would like to see in the future
  - name: 💬 F1-World-API community support
    url: https://github.com/enrique-lozano/F1-World-API/discussions/categories/q-a
    about: Get help or advice on how to use the application
